spring:
  profiles: local

  data:
    mongodb:
      database: testDB
      host: localhost
      port: 27017
      authentication-database: admin
      username: productUser
      password: productPwd
  #uri: mongodb://localhost:27017/admin
