spring:
  profiles:
    active:
      - cold-box
      - prod

  application:
    name: Products
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework: INFO
    com.castillo.pavel.store: INFO
    org.springframework.data.mongodb: DEBUG
    org.mongodb: DEBUG
  pattern:
    console: "%d{ABSOLUTE} %5p %40.40c:%7L - %m%n"

