spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: productUser
      password: productPwd
      #uri: mongodb://localhost:27017/admin
      database: products
logging:
  level:
    org.springframework: INFO
    com.castillo.pavel.store: INFO
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{ABSOLUTE} %5p %40.40c:%7L - %m%n"
