spring:
  profiles: prod

  data:

    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: productUser
      password: productPwd
      #uri: mongodb://localhost:27017/admin
      database: products
---


